HYDRATOR-1475 Create MQTT streaming source plugin
data-integrations/mqtt pull request #1
Opened 2017-04-13 20:28 UTC by Denton-L

2017-04-19 02:15 UTC, nitinmotgi commented
Checked document is not modified and also class name is not changed.

2017-04-19 22:31 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +These files can be used to deploy your plugins.
your plugin.

2017-04-19 22:32 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +[![Build Status](https://travis-ci.org/hydrator/sftp-actions.svg?branch=develop)](https://travis-ci.org/hydrator/mqtt) [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https:/
I have some simpler code you can use here and remove the HTML.

2017-04-19 22:32 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +This MQTT Streaming Source allows you to subscribe to a specific topic with a MQTT broker as a
an MQTT (everywhere!)

2017-04-19 22:33 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +For example, if we have the topic "a/b/c/d", the following will match:
the following will match: -> these will match:

2017-04-19 22:34 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +While the following will _not_ match:
```
while these will _not_ match:

2017-04-19 22:36 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +
Additionally, the zero-length topic, ...
or how about:
```
Additionally, the zero-length topic, "", is permitted:

* "/a/b" will match "+/a/topic" and "/#"
* "a//b" will match "a/+/b"
```
as that might be quicker read.

2017-04-19 22:47 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +[![Build Status](https://travis-ci.org/hydrator/sftp-actions.svg?branch=develop)](https://travis-ci.org/hydrator/mqtt) [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https:/
https://github.com/hydrator/wrangler/pull/77/files#diff-04c6e90faac2675aa89e2176d2eec7d8L1

2017-04-19 23:07 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +
What about:
```
The MQTT Streaming Source allows you to subscribe to a specific topic with an MQTT broker as a
client for messages in a streaming context.
```
The sentence is still running-on; if you could break into two or improve it, that'd be good.

2017-04-19 23:14 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +you to specify the topic to subscribe to as a MQTT client.
```
The MQTT Streaming Source allows you to subscribe to an MQTT broker in a streaming context. 
You specify the topic to subscribe to as an MQTT client.

2017-04-19 23:17 UTC, awholegunch commented on docs/MQTT-streamingsource.md
> +typically be 1883. Otherwise, if the MQTT protocol is SSL, the port will typically be 8889.
```
The MQTT Streaming Source will listen to an MQTT broker and subscribe to a given topic. 
To do this, you need to supply the host and port of the MQTT broker. If the MQTT protocol is TCP, 
the default port will be 1883. If the MQTT protocol is SSL, the default port is 8889.

2017-04-19 23:18 UTC, awholegunch commented on pom.xml
> +      <organizationUrl>http://www.cdap.io</organizationUrl>
```
<organizationUrl>http://cask.co</organizationUrl>

2017-04-19 23:33 UTC, awholegunch commented on src/main/java/co/cask/hydrator/plugin/spark/MQTTStreamingSource.java
> +@Description("Listens to a MQTT broker and subscribes to a given topic.")
…an MQTT broker…

2017-04-19 23:34 UTC, awholegunch commented
One comment, otherwise docs LGTM.

2017-04-24 23:37 UTC, nitinmotgi requested changes
Please make the changes and let me know.

2017-04-24 23:37 UTC, nitinmotgi commented on src/main/java/co/cask/hydrator/plugin/spark/MQTTStreamingSource.java
> +  public static class Conf extends ReferencePluginConfig {
config

2017-04-24 23:37 UTC, nitinmotgi commented on pom.xml
> +    <app.parents>system:cdap-data-pipeline[4.1.0,4.2.0-SNAPSHOT),system:cdap-data-streams[4.1.0,4.2.0-SNAPSHOT)</app.parents>
this should be only streams right -- as this is not supported in batch ?

2017-04-24 23:37 UTC, nitinmotgi commented on pom.xml
> +    <cdap.version>4.1.0</cdap.version>
4.1.1

2017-04-24 23:37 UTC, nitinmotgi commented on src/main/java/co/cask/hydrator/plugin/spark/MQTTStreamingSource.java
> + * Source that monitors a directory and reads files from it.
It doesn't read from the directory right ?

2017-04-24 23:37 UTC, nitinmotgi commented on src/main/java/co/cask/hydrator/plugin/spark/MQTTStreamingSource.java
> +  public static final String FIELD_NAME = "mqtt_output";
instead of ```mqtt_output``` call it ```event```

2017-04-24 23:37 UTC, nitinmotgi commented on src/main/java/co/cask/hydrator/plugin/spark/MQTTStreamingSource.java
> +  public static class Conf extends ReferencePluginConfig {
Please change this to Config

2017-04-24 23:37 UTC, nitinmotgi commented on widgets/MQTT-streamingsource.json
> +          "label": "Broker URL"
Add a placeholder to include a example url on how that looks.

2017-04-24 23:37 UTC, nitinmotgi commented on widgets/MQTT-streamingsource.json
> +          "name": "outputColumn",
this is not needed as the column is fixed.

2017-04-24 23:37 UTC, nitinmotgi commented on widgets/MQTT-streamingsource.json
> +            "type": "string"
this should be byte array and not string. Make changes accordingly.

2017-04-24 23:50 UTC, Denton-L commented on widgets/MQTT-streamingsource.json
> +            "type": "string"
`MQTTUtils` returns `String`s as output. Do you think that they should be converted to a `byte[]`?

2017-04-24 23:55 UTC, nitinmotgi commented on widgets/MQTT-streamingsource.json
> +            "type": "string"
OK, if that itself returns string, there is nothing we can do. So, let it be string then.

2017-04-24 23:57 UTC, nitinmotgi commented on docs/MQTT-streamingsource.md
> +[![Join CDAP community](https://cdap-users.herokuapp.com/badge.svg?t=mqtt)](https://cdap-users.herokuapp.com)
This goes in plugin documentation as reference and it should not have all these links.

2017-04-24 23:58 UTC, nitinmotgi commented on docs/MQTT-streamingsource.md
> +Build
from here the content shouldn't be in here.

2017-04-24 23:59 UTC, nitinmotgi commented
Also could you add spec for market similar to : https://github.com/hydrator/whole-file-reader/tree/release/1.0/market/1.0.0

2017-04-25 00:25 UTC, nitinmotgi requested changes

2017-04-25 00:25 UTC, nitinmotgi commented on pom.xml
> +    <cdap.version>4.1.0</cdap.version>
4.1.1

2017-04-25 05:46 UTC, nitinmotgi approved these changes

2017-04-25 05:47 UTC, merged

2017-04-25 05:57 UTC, Denton-L commented
@nitinmotgi Why was this merged before the commits were cleaned up and squashed?